#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-jose-cryptodome
Version  : 1.3.2
Release  : 1
URL      : https://files.pythonhosted.org/packages/62/46/7709c4b6fd1d3d97fc86d2904b12645831787ad3a240e7a3ab502cec54cf/python-jose-cryptodome-1.3.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/62/46/7709c4b6fd1d3d97fc86d2904b12645831787ad3a240e7a3ab502cec54cf/python-jose-cryptodome-1.3.2.tar.gz
Summary  : JOSE implementation in Python using pycryptodome
Group    : Development/Tools
License  : MIT
Requires: python-jose-cryptodome-python3
Requires: python-jose-cryptodome-python
Requires: ecdsa
Requires: six
BuildRequires : buildreq-distutils3

%description
===========
        
        A JOSE implementation in Python using pycryptodome instead pycrypto.
        Stop using pycrypto use pycryptodome_.
        
        |Build Status| |Coverage Status| |Docs|
        
        Docs are available on ReadTheDocs_.
        
        The JavaScript Object Signing and Encryption (JOSE) technologies - JSON
        Web Signature (JWS), JSON Web Encryption (JWE), JSON Web Key (JWK), and
        JSON Web Algorithms (JWA) - collectively can be used to encrypt and/or
        sign content using a variety of algorithms. While the full set of
        permutations is extremely large, and might be daunting to some, it is
        expected that most applications will only use a small set of algorithms
        to meet their needs.
        
        
        Principles
        ----------
        
        This is a JOSE implementation that is not compatible with Google App Engine
        as it uses pycryptodome.
        
        
        Installation
        ------------

%package python
Summary: python components for the python-jose-cryptodome package.
Group: Default
Requires: python-jose-cryptodome-python3

%description python
python components for the python-jose-cryptodome package.


%package python3
Summary: python3 components for the python-jose-cryptodome package.
Group: Default
Requires: python3-core

%description python3
python3 components for the python-jose-cryptodome package.


%prep
%setup -q -n python-jose-cryptodome-1.3.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534860319
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
